---

language: python
python: 3.4
env:
  - TOX_ENV=pypy-1.6.X
  - TOX_ENV=pypy-1.5.X
  - TOX_ENV=py34-1.6.X
  - TOX_ENV=py34-1.5.X
  - TOX_ENV=py33-1.6.X
  - TOX_ENV=py33-1.5.X
  - TOX_ENV=py27-1.6.X
  - TOX_ENV=py27-1.5.X
  - TOX_ENV=py26-1.6.X-tp9
  - TOX_ENV=py26-1.6.X-tp10
  - TOX_ENV=py26-1.6.X-tp11
  - TOX_ENV=py26-1.5.X
install:
  - pip install coveralls
  - pip install tox
script:
  - tox -e $TOX_ENV
  - coverage report -m
after_success:
  coveralls --verbose
